sonar.projectKey=go-api
sonar.projectName=Go API
sonar.projectVersion=1.0

# Rutas
sonar.sources=.
sonar.exclusions=**/vendor/**,**/*_test.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Lenguaje
sonar.language=go
sonar.go.coverage.reportPaths=coverage.out

# SonarQube server (opcional si lo configuras desde Jenkins)
# sonar.host.url=http://localhost:9000
